// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAtrs5RWdDoiYMC38doSEB1tGTfyWTQaE',
    appId: '1:1083581626403:web:ce9650fbf25d95da07d996',
    messagingSenderId: '1083581626403',
    projectId: 'buzzmate-8d108',
    authDomain: 'buzzmate-8d108.firebaseapp.com',
    storageBucket: 'buzzmate-8d108.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfkyU6fdEdfBpC_Geh6zJUmp5KaKpHQ88',
    appId: '1:1083581626403:android:5077a337f3fb076f07d996',
    messagingSenderId: '1083581626403',
    projectId: 'buzzmate-8d108',
    storageBucket: 'buzzmate-8d108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsas8tpql-M7YeNTGff-6592BbmpVOYRU',
    appId: '1:1083581626403:ios:12bb7b2699938ae007d996',
    messagingSenderId: '1083581626403',
    projectId: 'buzzmate-8d108',
    storageBucket: 'buzzmate-8d108.appspot.com',
    iosBundleId: 'com.hisham.buzzmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsas8tpql-M7YeNTGff-6592BbmpVOYRU',
    appId: '1:1083581626403:ios:e50e9758b3b432f607d996',
    messagingSenderId: '1083581626403',
    projectId: 'buzzmate-8d108',
    storageBucket: 'buzzmate-8d108.appspot.com',
    iosBundleId: 'com.example.buzzmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAtrs5RWdDoiYMC38doSEB1tGTfyWTQaE',
    appId: '1:1083581626403:web:c71ec253bb32a79d07d996',
    messagingSenderId: '1083581626403',
    projectId: 'buzzmate-8d108',
    authDomain: 'buzzmate-8d108.firebaseapp.com',
    storageBucket: 'buzzmate-8d108.appspot.com',
  );
}
